### ISSUE TITLE
Ha error in logs

### ISSUE THREAD

**Issue by kash1982** [pySmartThings/pysmartthings#193]
```
Logger: pysmartthings
Source: /usr/local/lib/python3.13/site-packages/pysmartthings/smartthings.py:359
First occurred: 23:13:03 (1 occurrences)
Last logged: 23:13:03

Error occurred while subscribing to events
Traceback (most recent call last):
File "/usr/local/lib/python3.13/site-packages/aiohttp/client_proto.py", line 92, in connection_lost
uncompleted = self._parser.feed_eof()
File "aiohttp/_http_parser.pyx", line 508, in aiohttp._http_parser.HttpParser.feed_eof
aiohttp.http_exceptions.TransferEncodingError: 400, message:
Not enough data for satisfy transfer length header.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "/usr/local/lib/python3.13/site-packages/pysmartthings/smartthings.py", line 325, in subscribe
async for event in aiosseclient(
...<30 lines>...
dle_callback(device_lifecycle_event.device_id)
File "/usr/local/lib/python3.13/site-packages/aiosseclient.py", line 132, in aiosseclient
async for line in response.content:
...<14 lines>...
lines.append(line)
File "/usr/local/lib/python3.13/site-packages/aiohttp/streams.py", line 52, in anext
rv = await self.read_func()
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.13/site-packages/aiohttp/streams.py", line 352, in readline
return await self.readuntil()
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.13/site-packages/aiohttp/streams.py", line 386, in readuntil
await self._wait("readuntil")
File "/usr/local/lib/python3.13/site-packages/aiohttp/streams.py", line 347, in _wait
await waiter
aiohttp.client_exceptions.ClientPayloadError: Response payload is not completed: <TransferEncodingError: 400, message='Not enough data for satisfy transfer length header.'>
```

**Comment by joostlek** [comment]
Okay so can you add a bit of context? What did you do? How many devices do you have?

I don't have a direct cause for this as we already have hundreds of people testing this over the last week, so anything that might be remarkable for your set up would be helpful

**Comment by kash1982** [comment]
Ok so error came after the new core and smartthings update.

We have a few smarttags and the larger appliances are a oven, hob and air conditioner. One motion sensor and one wall plug.  

Everything seems to functioning OK.

**Comment by joostlek** [comment]
Okay! I will keep this issue open, in theory it should just recover, but if there are more users having this, I am interested in the why and hows

**Comment by Dillton** [comment]
Hey. Just got the same in logs this night already with HA 2025.3.1 installed. Did nothing with the devices at the time, I was alreadz sleeping. Having only washer and dryer via ST.
```
Logger: pysmartthings
Source: /usr/local/lib/python3.13/site-packages/pysmartthings/smartthings.py:407
First occurred: 00:18:43 (1 occurrences)
Last logged: 00:18:43

Error occurred while subscribing to events
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/aiohttp/client_proto.py", line 92, in connection_lost
    uncompleted = self._parser.feed_eof()
  File "aiohttp/_http_parser.pyx", line 508, in aiohttp._http_parser.HttpParser.feed_eof
aiohttp.http_exceptions.TransferEncodingError: 400, message:
  Not enough data for satisfy transfer length header.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/pysmartthings/smartthings.py", line 371, in subscribe
    async for event in aiosseclient(
    ...<32 lines>...
                    dle_callback(device_lifecycle_event.device_id)
  File "/usr/local/lib/python3.13/site-packages/aiosseclient.py", line 132, in aiosseclient
    async for line in response.content:
    ...<14 lines>...
            lines.append(line)
  File "/usr/local/lib/python3.13/site-packages/aiohttp/streams.py", line 52, in __anext__
    rv = await self.read_func()
         ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/aiohttp/streams.py", line 352, in readline
    return await self.readuntil()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/aiohttp/streams.py", line 386, in readuntil
    await self._wait("readuntil")
  File "/usr/local/lib/python3.13/site-packages/aiohttp/streams.py", line 347, in _wait
    await waiter
aiohttp.client_exceptions.ClientPayloadError: Response payload is not completed: <TransferEncodingError: 400, message='Not enough data for satisfy transfer length header.'>
```

And also this one but I guess thats a different problem.
```
Logger: pysmartthings
Source: /usr/local/lib/python3.13/site-packages/pysmartthings/smartthings.py:407
First occurred: 08:19:22 (13 occurrences)
Last logged: 09:27:38

Error occurred while subscribing to events
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/pysmartthings/smartthings.py", line 366, in subscribe
    subscription = await self._create_subscription(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        location_id, installed_app_id
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/pysmartthings/smartthings.py", line 359, in _create_subscription
    return Subscription.from_json(resp)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "<string>", line 7, in __mashumaro_from_json__
mashumaro.exceptions.MissingField: Field "subscription_id" of type str is missing in Subscription instance
```

**Comment by joostlek** [comment]
The last one is related to https://github.com/home-assistant/core/issues/139993. Do you mind sharing logs? As there probably has been a reason why it started hitting this

**Comment by Dillton** [comment]
I've just enabled debug logging so once this occurs again I will share.

**Comment by joostlek** [comment]
There most likely are already logs in there, and they are currently very valuable :)

**Comment by Dillton** [comment]
Ok this is all I can get be be cause normally I have all logging set to `error` only.

[home-assistant_2025-03-08T13-47-31.071Z.log](https://github.com/user-attachments/files/19143952/home-assistant_2025-03-08T13-47-31.071Z.log)

**Comment by joostlek** [comment]
Okay interesting, I would expect something to be raised as exception. Thanks anyway

**Comment by joostlek** [comment]
Fixed by #283

**Comment by LiquidPT** [comment]
I'm still seeing this in HA 2025.04.01 which includes pySmartThigns 3.0.2

```
Logger: pysmartthings
Source: /usr/local/lib/python3.13/site-packages/pysmartthings/smartthings.py:505
First occurred: 12:16:25 AM (1 occurrences)
Last logged: 12:16:25 AM

Connection error occurred while subscribing to events
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/aiohttp/client_proto.py", line 93, in connection_lost
    uncompleted = self._parser.feed_eof()
  File "aiohttp/_http_parser.pyx", line 508, in aiohttp._http_parser.HttpParser.feed_eof
aiohttp.http_exceptions.TransferEncodingError: 400, message:
  Not enough data for satisfy transfer length header.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/pysmartthings/smartthings.py", line 494, in subscribe
    await self._internal_subscribe(session, subscription_url)
  File "/usr/local/lib/python3.13/site-packages/pysmartthings/smartthings.py", line 416, in _internal_subscribe
    async for event in event_source:
    ...<39 lines>...
                break
  File "/usr/local/lib/python3.13/site-packages/aiohttp_sse_client2/client.py", line 157, in __anext__
    async for line_in_bytes in self._response.content:
    ...<21 lines>...
            self._process_field(line, '')
  File "/usr/local/lib/python3.13/site-packages/aiohttp/streams.py", line 52, in __anext__
    rv = await self.read_func()
         ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/aiohttp/streams.py", line 352, in readline
    return await self.readuntil()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/aiohttp/streams.py", line 386, in readuntil
    await self._wait("readuntil")
  File "/usr/local/lib/python3.13/site-packages/aiohttp/streams.py", line 347, in _wait
    await waiter
aiohttp.client_exceptions.ClientPayloadError: Response payload is not completed: <TransferEncodingError: 400, message='Not enough data for satisfy transfer length header.'>
```

**Comment by joostlek** [comment]
We now handle it correctly but we just log it
